The 'keyError' will be displayed if the dicitionary data values are not present in the MongoDB for the users.
Date format for the "date_added" dictionary field in MongoDB - "date_added" : ISODate("2021-05-06T13:52:46.492Z")
